include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_single_quotes: true
    always_use_package_imports: true
    depend_on_referenced_packages: false
    combinators_ordering: false
